### ISSUE TITLE
Needs a basic Node/Express backend for early prototyping

### ISSUE THREAD

**Issue by ianwessen** [ianwessen/go-stop-client#12]
We want to deploy this ASAP to get actual Go users in front of this. Before Cam's backend is up, we want to get this live and playable. We believe a free-tier Heroku Node app with an Express server is the best option but you are free to choose anything that's fast, easy, free, and can serve our frontend.

**Comment by brandoniscool** [comment]
Heroku is a great idea to start. I foresee a migration to AWS when things pick up.
